AWSTemplateFormatVersion: '2010-09-09'
Description: 'Servicecatalog'
Resources:
  Portfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      DisplayName: example-portfolio
      Description: !Sub 'Example portfolio created by CloudFormation stack ${AWS::StackName}'
      ProviderName: !Sub 'CloudFormation-${AWS::StackName}'

  PortfolioPrincipalAssociation:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PortfolioId: !Ref Portfolio
      PrincipalType: IAM
      PrincipalARN: arn:aws:iam::554248189203:user/test-service-saba
  Product:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:          
      Name: api-product
      Description: !Sub 'Example product created by CloudFormation stack ${AWS::StackName}'
      Owner: !Sub 'CloudFormation-${AWS::StackName}'      
      ProvisioningArtifactParameters:
        - Name: '0.1.0'
          Description: API with lambda
          Info:
            LoadTemplateFromURL: https://s3.amazonaws.com/service-catalog-pipeline-demo/api2.yaml    
  ProductAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref Portfolio
      ProductId: !Ref Product
