AWSTemplateFormatVersion: '2010-09-09'
Description: 'Servicecatalog'
Resources:
  Portfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      DisplayName: product-portfolio
      Description: !Sub 'Example portfolio created by CloudFormation stack ${AWS::StackName}'
      ProviderName: !Sub 'CloudFormation-${AWS::StackName}'

  PortfolioPrincipalAssociation:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PortfolioId: !Ref Portfolio
      PrincipalType: IAM
      PrincipalARN: arn:aws:iam::554248189203:user/test-service-saba

  Product1:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: s3-cdn
      Description: !Sub 'Example product created by CloudFormation stack ${AWS::StackName}'
      Owner: !Sub 'CloudFormation-${AWS::StackName}'
      # Distributor: String
      ProvisioningArtifactParameters:
        - Name: '1.0'
          Description: Initial product release
          Info:
            LoadTemplateFromURL: https://s3.amazonaws.com/service-catalog-pipeline-demo/cft-s3-cloudfront.yaml

  Product2:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: api-lambda
      Description: !Sub 'Example product created by CloudFormation stack ${AWS::StackName}'
      Owner: !Sub 'CloudFormation-${AWS::StackName}'
      # Distributor: String
      ProvisioningArtifactParameters:
        - Name: '1.0'
          Description: Initial product release
          Info:
            LoadTemplateFromURL: https://s3.amazonaws.com/service-catalog-pipeline-demo/api2.yaml

        - Name: '1.1'
          Description: version 2 with minor changes added supporting programming languages
          Info:
            LoadTemplateFromURL: https://s3.amazonaws.com/service-catalog-pipeline-demo/api2.yaml?versionId=h6fDClw24wmTzXmlKA2bva4JN7L.lYRj      


  
  Product3:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: cft-ecs-without-pipeline
      Description: !Sub 'Example product created by CloudFormation stack ${AWS::StackName}'
      Owner: !Sub 'CloudFormation-${AWS::StackName}'
      # Distributor: String
      ProvisioningArtifactParameters:
        - Name: '1.0'
          Description: Initial product release
          Info:
            LoadTemplateFromURL: https://s3.amazonaws.com/service-catalog-pipeline-demo/cft-ecs-without-pipeline.yaml?versionId=4Z437ydhAfNFNQBVp_R4KXzSxqNjDOQA

  Product4:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: ecs-withpipeline
      Description: !Sub 'Example product created by CloudFormation stack ${AWS::StackName}'
      Owner: !Sub 'CloudFormation-${AWS::StackName}'
      # Distributor: String
      ProvisioningArtifactParameters:
        - Name: '1.0'
          Description: Initial product release
          Info:
            LoadTemplateFromURL: https://s3.amazonaws.com/service-catalog-pipeline-demo/cft-ecs-stack.yaml 

        
  ProductAssociation1:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref Portfolio
      ProductId: !Ref Product1

  ProductAssociation2:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref Portfolio
      ProductId: !Ref Product2

  ProductAssociation3:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref Portfolio
      ProductId: !Ref Product3

  ProductAssociation4:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref Portfolio
      ProductId: !Ref Product4
